django_movies/core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import MovieListView, MovieCreateView, MovieDeleteView, MovieUpdateView, MovieDetailView

app_name = 'core'

urlpatterns = [
    path('movie/list', MovieListView.as_view(), name='movie_list'),
    path('movie/detail/<pk>', MovieDetailView.as_view(), name='movie_detail'),
    path('movie/create', MovieCreateView.as_view(success_url='create'), name='movie_create'),
    path('movie/update/<pk>', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<pk>', MovieDeleteView.as_view(), name='movie_delete')

]

django_movies/django_movies/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

from core.views import hello
from django_movies.view import IndexView

from accounts.views import SubmittableLoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('hello/', hello),
    path("core/", include('core.urls', namespace='core')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

django_movies/core/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from model_utils import Choices

AGE_LIMIT = Choices(
    (0, 'kids', 'kids'),
    (1, 'teens', 'teens'),
    (2, 'adults', 'adults'),
)


class Country(models.Model):
    country_name = models.CharField(max_length=50, null=True, unique=True)

    def __str__(self):
        return self.country_name


class Genre(models.Model):
    name = models.CharField(max_length=20, unique=True)
    age_limit = models.IntegerField(blank=True, null=True, choices=AGE_LIMIT)

    def __str__(self):
        return self.name


class Director(models.Model):
    full_name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.full_name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    rating = models.IntegerField(
        null=True, validators=[MaxValueValidator(10), MinValueValidator(1)]
    )
    released = models.DateField()
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    genre = models.ForeignKey(Genre, null=True, on_delete=models.DO_NOTHING)
    director = models.ForeignKey(Director, null=True, on_delete=models.SET_NULL)
    countries = models.ManyToManyField(Country, related_name='movies')

    def __str__(self):
        return f"{self.title} from {self.released}"

    class Meta:
        unique_together = ('title', 'released')

#
# #1.
# Movie.objects.filter(countries__name__in=['Poland', 'Germany']).distinct()
# #2.
# Movie.objects.filter(released__year__gt=2020, rating__gte=8)
# #3.
# from django.db.models import Count
# genres = Movie.objects.values('genre').annotate(genres_count=Count('genre')).filter(genres_count__gte=2).values_list('genre')Movie.objects.filter(genre__in=genres)

django_movies/core/forms.py
import re
from datetime import date

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.core.exceptions import ValidationError

from core.models import Genre, Movie, Director, Country
from django.core.validators import MinLengthValidator
from django.forms import SelectDateWidget

from accounts.forms import SubmittableForm


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized.')


class PastMonthField(forms.DateField):
    def validate(self, value):
        super().validate(value)
        if value >= date.today():
            raise ValidationError('Only past dates allowed here.')

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
    title = forms.CharField(validators=[MinLengthValidator(3)])
    rating = forms.IntegerField(min_value=1, max_value=10)
    released = PastMonthField

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'title',
            Row(Column('genre'), Column('rating'), Column('released')),
            'director',
            'description',
            'countries',
            'created',
            Submit('submit', 'Submit')
        )
    # class MovieForm(forms.Form):
    #     title = forms.CharField(max_length=100)
    #     genre = forms.ModelChoiceField(queryset=Genre.objects.all())
    #     rating = forms.IntegerField(min_value=1, max_value=10)
    #     released = PastMonthField()
    #     description = forms.CharField(widget=forms.Textarea, required=False)
    #     director = forms.ModelChoiceField(queryset=Director.objects.all())
    #     countries = forms.ModelMultipleChoiceField(queryset=Country.objects.all())

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        cleaned = '. '.join(sentence.capitalize() for sentence in sentences)
        return cleaned

    def clean(self):
        result = super().clean()
        if result['genre'].name == 'comedy' and result['rating'] > 5:
            raise ValidationError('The best comedy is worth a 4.')
        return result

django_movies/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django import views
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView, DeleteView, UpdateView, DetailView
from django.http import HttpResponse

from core.models import Movie, AGE_LIMIT

from core.forms import MovieForm
from pip._internal.utils import logging


LOGGER = logging.getLogger()


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class MovieUpdateView(StaffRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = 'core/form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('index')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)


class MovieDeleteView(LoginRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy('index')


class MovieCreateView(LoginRequiredMixin, CreateView):
    title = 'Add Movie'
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('movie_create')

    def form_invalid(self, form):
        LOGGER.warning('Invalid data provided.')
        return super().form_invalid(form)

    # def form_valid(self, forms):
    #     forms.save()
    #     return super().form_valid(forms)


class MovieListView(StaffRequiredMixin, ListView):
    template_name = 'movies.html'
    model = Movie

    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        result['limits'] = AGE_LIMIT
        return result


class MovieDetailView(DetailView):
    template_name = 'movie_detail.html'
    model = Movie


def movies(request):
    return render(
        request,
        template_name='movies.html',
        context={'movies': Movie.objects.all(),
                 'limits': AGE_LIMIT}
        # context={'movies': Movie.objects.exclude(genre__age_limit=AGE_LIMIT.adult)},
    )


def hello(request):
    return render(
        request,
        template_name='hello.html',
        context={'adjectives': ['beatufiul', 'cruel', 'wonderfull']}
    )





# def hello(request):
#     return HttpResponse('Hello world!')

django_movies/core/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello, world</title>
</head>
<body>
    <h1>Hello, my friend...</h1>
    {% for adjective in adjectives %}
        {% if adjective != 'cruel' %}
            <p>This is a {{ adjective }} word...</p>
        {% endif %}
    {% endfor %}
</body>
</html>

django_movies/core/templates/movie_confirm_delete.html
{% extends "core/base.html" %}

{% load bootstrap4 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure you want to delete movie {{ object.title }} from the database?
        </p>
        <input type="submit" value="Yes" class="btn btn-danger">
        <a href="{% url 'index' %}"><button class="btn btn-outline-secondary" type="button">No</button></a>
    </form>
{% endblock %}

django_movies/core/templates/movie_detail.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  {{ movie|attr_as_p:'title' }}
  {{ movie|attr_as_p:'released' }}
  {{ movie|attr_as_p:'genre' }}
  {{ movie|attr_as_p:'rating' }}
  {{ movie|attr_as_p:'description' }}
{% endblock %}

django_movies/core/templates/movie_list.html
{% extends "base.html" %}

{% load movie_extras %}

{% block content %}
  <ul>
    {% for movie in object_list %}
      <li>
        {% movie_format movie short=True %}
        <a href="{% url 'core:movie_detail' movie.pk %}">detail</a> /
        <a href="{% url 'core:movie_update' movie.pk %}">update</a> /
        <a href="{% url 'core:movie_delete' movie.pk %}">delete</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

django_movies/core/templates/movies.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Django Movies!</h1>
    <ul>
            {% for movie in object_list %}
            {% comment %}   {% if movie.genre.age_limit != limits.adults %}    {% endcomment %}
                    <li>
                        {{ movie.title }} ({{ movie.released.year }}) by {{ movie.director }}, genre: {{ movie.genre.name }}
                    </li>
            {% comment %}   {% endif %}    {% endcomment %}
            {% endfor %}
    </ul>

{% endblock %}